spring:
 profile:
    active: prod
 datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/ohwaiter
     username: postgres
     password: aluno
 jpa:
   hibernate:
        ddl-auto: update
   show-sql: true
   database: postgresql
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   open-in-view: false
   generate-ddl: true
 logging: INFO
 server:
   port: 8080

