spring:
  profile:
    active: prod
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/ohwaiter
     username: postgres
     password: aluno
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_IP:localhost}:${KEYCLOAK_PORT:8080}/realms/ohwaiter
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  logging: INFO
server:
  port: 8082
